Validation panel
APHA-BAC/NextflowSerotypingPipeline pull request #31
Opened 2022-02-04 11:31 UTC by jhtpotter

Using Docker, run Master branch on the Validation Panel of 250 isolates stored on FSx-019. Compare the outcome of this run with the expected results to establish Pass or Fail

2022-02-04 11:56 UTC, afishman requested changes
Hey Josh looks good, just requesting to remove the test data.

2022-02-04 11:56 UTC, afishman commented on validation250/validation_test_SummaryTable.csv
> +StrainID,Consensus,#ReadsR1,GC%R1,R1Kmerid,ContaminationFlag,MOST,Most_light,st,MLST,MLST mean cov,SeqSero,SS comment,N50,serogroup,serovar,serovar_antigen,serovar_cgmlst,vaccine,mono,sseJ,ReadLenRan
Hey Josh can you remove this file?

2022-02-04 12:20 UTC, jhtpotter commented on validation250/validation_test_SummaryTable.csv
> +StrainID,Consensus,#ReadsR1,GC%R1,R1Kmerid,ContaminationFlag,MOST,Most_light,st,MLST,MLST mean cov,SeqSero,SS comment,N50,serogroup,serovar,serovar_antigen,serovar_cgmlst,vaccine,mono,sseJ,ReadLenRan
Done!

2022-02-07 09:38 UTC, afishman approved these changes

2022-02-07 15:50 UTC, merged