Update readme
APHA-BAC/NextflowSerotypingPipeline pull request #40
Opened 2022-02-15 16:47 UTC by afishman

Updates the readme to contain the latest info

2022-02-15 17:13 UTC, ahussaini821 requested changes
Minor grammar changes. Some changes I requested are sort of subjective.
Looks great otherwise.

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +To run the pipeline on a batch a samples, the raw `.fastq.gz` files must be stored in `~/WGS_Data/<runID>`.  Each read-pair sample is represented by a pair of files named `*_R1.fastq.gz` and `*_R2.fa
'batch a samples' to 'batch of samples'

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +To run the pipeline on a batch a samples, the raw `.fastq.gz` files must be stored in `~/WGS_Data/<runID>`.  Each read-pair sample is represented by a pair of files named `*_R1.fastq.gz` and `*_R2.fa
Not sure if the 'needs to be defined' at the end makes grammatical sense but not 100% sure

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +A docker image containing all required dependancies is provided [here](https://hub.docker.com/r/jguzinski/salmonella-seq).
'dependancies' to 'dependencies'

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +This pull the latest image (if it's not already fetched) from dockerhub and run the container on data
'This pull' to 'This pulls'

'run' to 'runs' (?)

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +The pipelines processes data in three stages, as shown below. During the preprocessing stage; low quality bases, adapter sequences are removed from the fastq sample file and then subsampled to a maxi
'pipelines processes' to either 'pipeline processes' or 'pipelines process'

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +The pipelines processes data in three stages, as shown below. During the preprocessing stage; low quality bases, adapter sequences are removed from the fastq sample file and then subsampled to a maxi
'low quality bases, adapter sequences' to 'low quality bases and adapter sequences'

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +To release a new version of the software, the `master` branch needs only to be merged into `prod` branch. To perform this merge, a pull-request from the `master` branch into the `prod` branch needs t
"into 'prod branch'" to "into the 'prod branch'"

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +1. A developer makes a pull-request from the `master` to `prod` branch. The CODEOWNER is automatically notified by e-mail.
"the `master` to `prod` branch" to "the `master` to the `prod` branch"

2022-02-15 17:13 UTC, ahussaini821 commented on README.md
> +1. Following approval, the developer tags the current of head of master as the next version. Versions are numbered incrementally with integers, for example `v1`, `v2`, etc. This can be performed by n
"tags the current of head of master" to "tags the current head of master"

2022-02-16 10:58 UTC, afishman commented on README.md
> +To run the pipeline on a batch a samples, the raw `.fastq.gz` files must be stored in `~/WGS_Data/<runID>`.  Each read-pair sample is represented by a pair of files named `*_R1.fastq.gz` and `*_R2.fa
I agree, removed.

2022-02-16 11:18 UTC, ahussaini821 approved these changes
Looks great!

2022-02-16 11:29 UTC, merged