Remove repo references
APHA-BAC/NextflowSerotypingPipeline pull request #50
Opened 2022-04-21 10:04 UTC by ahussaini821

Replaced the wget commands which referenced the repository with cp commands which copy from the local directories instead.

Didn't replace the commands in the old_scripts folder since this folder will likely be removed soon, and also didn't change the wget commands in the file for the 210 local install.

2022-04-22 08:16 UTC, afishman requested changes
Great to see the calls to github being removed. A few comments on what the install scripts are being used for. Happy to jump on a call if you're not sure and want to talk things through

2022-04-22 08:16 UTC, afishman commented on ebgs.csv
> +eBG,ST
what is this file for?

2022-04-22 08:16 UTC, afishman commented on install/install-Nextflow_SummaryTable_FolderPrep.sh
>  curl -s https://get.nextflow.io | bash
This install file is not part of the main install script that Docker runs. What is it used for?

2022-04-22 08:16 UTC, afishman commented on install/install-salmonella-pipeline-SCEv3.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/JaromirGuzinski/NextflowSerotypingPipeline/master/install-fastqc.sh
Same with this file - it's not part of `install.bash`

2022-04-22 08:16 UTC, afishman commented on install/setup-environment.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/APHA-BAC/NextflowSerotypingPipeline/master/summaryTable_reworked.py
The repo may not always be located in `~/NextflowSerotypingPipeline/`. More flexible to remove the `cd` on Line 11 and then
`cp ./summaryTable_reworked.py $HOME/summary`

IMO we shouldn't need to be copying these sorts of files to the home. But that's probably best left for a future PR.

2022-04-22 09:59 UTC, ahussaini821 commented on ebgs.csv
> +eBG,ST
Ah this wasn't supposed to be included in this commit. That's what I get for my bad habit of staging all changes at once.
Will change.

2022-04-22 10:01 UTC, ahussaini821 commented on install/install-salmonella-pipeline-SCEv3.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/JaromirGuzinski/NextflowSerotypingPipeline/master/install-fastqc.sh
This one I'm not sure. It might also just be an old script but can't confirm.

2022-04-22 10:01 UTC, ahussaini821 commented on install/setup-environment.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/APHA-BAC/NextflowSerotypingPipeline/master/summaryTable_reworked.py
Good point. Will change.

2022-04-22 11:08 UTC, ahussaini821 commented
Seem to be getting srst2 errors in some of the inclusivity tests. @afishman is this similar to the error you were referring to a couple of weeks back?

2022-04-22 12:38 UTC, afishman commented
yeah I think so. The error message is very unhelpful -- and this hard to track! We can try rerunning the test via TeamCity to see if the error is happening consistently. Would be great as well if we can reproduce the error in docker within the SCE.

2022-04-25 10:04 UTC, afishman commented on install/setup-environment.sh
> +cp ./summaryTable_reworked.py $HOME/summary
nice. this is better

2022-04-25 10:05 UTC, afishman commented on install/install-salmonella-pipeline-SCEv3.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/JaromirGuzinski/NextflowSerotypingPipeline/master/install-fastqc.sh
Can we remove this file?  We should be using the same install script for both SCE and Docker.

2022-04-25 10:20 UTC, ahussaini821 commented on old_scripts/install-Nextflow_SummaryTable_FolderPrep.sh
> -wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/APHA-BAC/NextflowSerotypingPipeline/master/SCE3_pipeline_update.nf
Just confirmed with Josh that everything in the old_scripts folder can be removed so I will go ahead and do that

2022-04-25 10:20 UTC, ahussaini821 commented on lims_rules/020422_APHA_NB501786_0396_SummaryTable_plusLIMS.csv
> +Isolate_ID,Consensus,LIMS_Status,LIMS_Reason,LIMS_SerotypeID,LIMS_Subgenus,LIMS_Serogroup,LIMS_Variant,LIMS_Vaccine,#Reads_raw,#Reads_filtered,GC%,KmerID,Contam_Flag,MOST,MOST_Light,MOST_ST,MLST,MLST
Oh don't think that was supposed to be included. Will sort it.

2022-04-25 12:46 UTC, afishman approved these changes
Thanks for removing these!

2022-04-25 12:46 UTC, merged